surahs = {
    1:'Al Fatiha',
    2:'Al Baqarah',
    3:'Aali Imran',
    4:'An Nisa',
    5:'Al Maidah',
    6:'Al Anam',
    7:'Al Araf',
    8:'Al Anfal',
    9:'At Taubah',
    10:'Yunus',
    11:'Hud',
    12:'Yusuf',
    13:'Ar Rad',
    14:'Ibrahim',
    15:'Al Hijr',
    16:'An Nahl',
    17:'Al Isra',
    18:'Al Kahf',
    19:'Maryam',
    20:'Ta Ha',
    21:'Al Anbiya',
    22:'Al Hajj',
    23:'Al Muminun',
    24:'An Nur',
    25:'Al Furqan',
    26:'Ash Shuara',
    27:'An Naml',
    28:'Al Qasas',
    29:'Al Ankabut',
    30:'Ar Rum',
    31:'Luqman',
    32:'As Sajdah',
    33:'Al Ahzab',
    34:'Saba',
    35:'Al Fatir',
    36:'Yaseen',
    37:'As Saffah',
    38:'Sad',
    39:'Az Zumar',
    40:'Ghafar',
    41:'Fusilat',
    42:'Ash Shura',
    43:'Az Zukhruf',
    44:'Ad Dukhan',
    45:'Al Jathiyah',
    46:'Al Ahqaf',
    47:'Muhammad',
    48:'Al Fath',
    49:'Al Hujurat',
    50:'Qaf',
    51:'Az Zariyat',
    52:'At Tur',
    53:'An Najm',
    54:'Al Qamar',
    55:'Ar Rahman',
    56:'Al Waqiah',
    57:'Al Hadid',
    58:'Al Mujadilah',
    59:'Al Hashr',
    60:'Al Mumtahanah',
    61:'As Saf',
    62:'Al Jumuah',
    63:'Al Munafiqun',
    64:'At Taghabun',
    65:'At Talaq',
    66:'At Tahrim',
    67:'Al Mulk',
    68:'Al Qalam',
    69:'Al Haqqah',
    70:'Al Maarij',
    71:'Nuh',
    72:'Al Jinn',
    73:'Al Muzammil',
    74:'Al Mudaththir',
    75:'Al Qiyamah',
    76:'Al Insan',
    77:'Al Mursalat',
    78:'An Naba',
    79:'An Naziat',
    80:'Abasa',
    81:'At Takwir',
    82:'Al Infitar',
    83:'Al Mutaffifin',
    84:'Al Inshiqaq',
    85:'Al Buruj',
    86:'At Tariq',
    87:'Al Ala',
    88:'Al Ghashiyah',
    89:'Al Fajr',
    90:'Al Balad',
    91:'Ash Shams',
    92:'Al Layl',
    93:'Adh Dhuha',
    94:'Al Inshirah',
    95:'At Tin',
    96:'Al Alaq',
    97:'Al Qadr',
    98:'Al Bayinah',
    99:'Al Zalzalah',
    100:'Al Adiyah',
    101:'Al Qariah',
    102:'At Takathur',
    103:'Al Asr',
    104:'Al Humazah',
    105:'Al Fil',
    106:'Quraish',
    107:'Al Maun',
    108:'Al Kauthar',
    109:'Al Kafirun',
    110:'An Nasr',
    111:'Al Masad',
    112:'Al Ikhlas',
    113:'Al Falaq',
    114:'An Naas'
}

surah_links = {
    'Al Fatiha': 'https://drive.google.com/uc?id=1JLj4iyocS52g6MJQglOEx9qtpxJY9SNz',
    'Al Baqarah': 'https://drive.google.com/uc?id=1FBzt5wvMVM7V1nwR08J-52yTTlDsPJMa',
    'Aali Imran': 'https://drive.google.com/uc?id=1N9QH4otwkYhoMBaPYvuv8jVpikgXeeFr',
    'An Nisa': 'https://drive.google.com/uc?id=1rLrhqZ8hny5c2V67Sk7CKp7b-w6yW0jJ',
    'Al Maidah': 'https://drive.google.com/uc?id=1Djcby_ZYkAFMzp6TQa0F69oEO4zq5RGl',
    'Al Anam': 'https://drive.google.com/uc?id=1uGxHG6jmW6h0rVkRebkfJRSuIo14monJ',
    'Al Araf': 'https://drive.google.com/uc?id=11YEpCaphBDLuAqkD6UWlZaSUVKvo8w68',
    'Al Anfal': 'https://drive.google.com/uc?id=1hTOqu0tcr4HCH5tqN5GP-6MGKFC3jtDd',
    'At Taubah': 'https://drive.google.com/uc?id=16ScV-IcdXuzSuEo55iSb_CqoB1dBc2Xb',
    'Yunus': 'https://drive.google.com/uc?id=1q6ga0rWzABZhmqP3fkr_kWga4R23fvxq',
    'Hud': 'https://drive.google.com/uc?id=1WF_vlfhkEDYmuZvvrkoN94JyHMYP8clS',
    'Yusuf': 'https://drive.google.com/uc?id=1FZmmEXxJc9U1plcI_X0GRxkz6nC46MPn',
    'Ar Rad': 'https://drive.google.com/uc?id=1Nios_dXn_VSxpwrSIJujHlIAs7WghO72',
    'Ibrahim': 'https://drive.google.com/uc?id=1aLCmZXAtwHnpSUjdRZlssecmRHXHlnWy',
    'Al Hijr': 'https://drive.google.com/uc?id=1TGScI3U6RvdO1bx2zgF_PvSERmU104vP',
    'An Nahl': 'https://drive.google.com/uc?id=1MNLmB6and2qyZhllLOER2kdQKh8yJ9pa',
    'Al Isra': 'https://drive.google.com/uc?id=12lXbt9ImTG4atbRruSpE883bWLmXyPtE',
    'Al Kahf': 'https://drive.google.com/uc?id=1_FbvzYMCP7oCjbTEZH47eT2d4d8h3dMX',
    'Maryam': 'https://drive.google.com/uc?id=1j3UpwL4hQImwe7NaYz3cHE8DcRORRVAq',
    'Ta Ha': 'https://drive.google.com/uc?id=1MaVSi2kZQHDqfuT63bN6mgJvVqj91fcV',
    'Al Anbiya': 'https://drive.google.com/uc?id=1fGDMdmlthiSt-jEYhmWHYXQFsIAJaHUi',
    'Al Hajj': 'https://drive.google.com/uc?id=1gJU5d-XcKreI_nyyLq98cA5cl78zgw8R',
    'Al Muminun': 'https://drive.google.com/uc?id=1oA07sK_tyqY1CcG5qhLEOygUAbCabNeL',
    'An Nur': 'https://drive.google.com/uc?id=1_k1ZtAioh71e8aPNesptuUfO5L_BEFFz',
    'Al Furqan': 'https://drive.google.com/uc?id=15P83ywzDXPl1rKuR4_FgcCYJM6hlAztv',
    'Ash Shuara': 'https://drive.google.com/uc?id=1W5dEyD4MkJ4SD26Ld3CFo3n2D-tVUsit',
    'An Naml': 'https://drive.google.com/uc?id=18ub97auuqb7779dvWoAprL1WI4zJmM9o',
    'Al Qasas': 'https://drive.google.com/uc?id=1GGvAwW8cY0IziGSloP7Ew7X2VAFnTJIT',
    'Al Ankabut': 'https://drive.google.com/uc?id=1ClLBJrEaAp7oA5cARbcMI-n0wQaWam4F',
    'Ar Rum': 'https://drive.google.com/uc?id=1bIEGpO0j1jX1rWPkOflHuNLKDgQAsGFN',
    'Luqman': 'https://drive.google.com/uc?id=1GGN69MBND9gJNMKMv2kpsLa9XCtKs45L',
    'As Sajdah': 'https://drive.google.com/uc?id=1p9EYqu8fQ8v-cZcS4T-FAtpWojR_d3-n',
    'AL Ahzab': 'https://drive.google.com/uc?id=1w2kWfSmsP6VUhyIAZISEXLIbkRCvRsuZ',
    'Saba': 'https://drive.google.com/uc?id=1VCgw_JN19wVGYhO_u-sTkfhDOVgibbf8',
    'Al Fatir': 'https://drive.google.com/uc?id=1KUL1US74SLDubp-baKBrZ8XmkvicNJTt',
    'Yaseen': 'https://drive.google.com/uc?id=1a_EHJnIdGHtLLzeLx4_VSG8UEtTTW8X1',
    'As Saffah': 'https://drive.google.com/uc?id=1VbSbSNud_tSlDqMFa8Y5Oyu1YwBa0eZI',
    'Sad': 'https://drive.google.com/uc?id=1dLB9wXGOp52yrR0MUIJjLP9y_X9ela7g',
    'Az Zumar': 'https://drive.google.com/uc?id=16g5Ktr0Z0WRjVSWlWqGtvOi1L8jSCLeY',
    'Ghafar': 'https://drive.google.com/uc?id=1zSPnIhibUoZJvz2htClZYfwt8vC9j5Nv',
    'Fusilat': 'https://drive.google.com/uc?id=1OBM_BS23W8bfEIE6-OIK4lQkLe8AiCu6',
    'Ash Shura': 'https://drive.google.com/uc?id=1M_AW2KA66a_OcbEZdB4UaYPlQrXNcpVs',
    'Az Zukhruf': 'https://drive.google.com/uc?id=1vwteqpnOTfAN3nGbhTfMinxGYM9LdNVd',
    'Ad Dukhan': 'https://drive.google.com/uc?id=1iqgMzNjAXZ8M61XpvkBEo1ugH5XK0JLg',
    'Al Jathiyah': 'https://drive.google.com/uc?id=1nFi3a5rb1mmxncajOV_m9fCwRadoq2_j',
    'Al Ahqaf': 'https://drive.google.com/uc?id=1jrBU7gFImBFl8Py4EFLRSyzhbDATqXM5',
    'Muhammad': 'https://drive.google.com/uc?id=1QlFvvfpebSyiKRfNkTexf1ASwy09ygtv',
    'Al Fath': 'https://drive.google.com/uc?id=1cYGkrDgjnNEOHhwr-ZQT8tRaT8Zm9Ofi',
    'Al Hujurat': 'https://drive.google.com/uc?id=1HiihieALsPfA2AZuia7q7z7BJ0ly7IqB',
    'Qaf': 'https://drive.google.com/uc?id=1zgDKF1aNtLfRYlfcRx8GNnjW2PIAyXt-',
    'Az Zariyat': 'https://drive.google.com/uc?id=1BE73HJWQmSw6aIiRwiklR9yVdTrLZuj1',
    'At Tur': 'https://drive.google.com/uc?id=1VZ8uEuBOe0BQEZu_b57XsLxu68fcLPQD',
    'An Najm': 'https://drive.google.com/uc?id=172B1LCvsL1VDLdY_Rox_yBE9sIB8EPZV',
    'Al Qamar': 'https://drive.google.com/uc?id=1a7dcL5bF9OUJMZ0qitTOZccat8hMWwWR',
    'Ar Rahman': 'https://drive.google.com/uc?id=19ler2UyJBZNtQFEBYgucEjWuU7s-0zgK',
    'Al Waqiah': 'https://drive.google.com/uc?id=1zozqmL0VifiMr-CSXTSfNbqdORUMPcKF',
    'Al Hadid': 'https://drive.google.com/uc?id=1g-aNohVqQdBqXGRvHvkvKYm1ZVydysyU',
    'Al Mujadilah': 'https://drive.google.com/uc?id=1ze7kvwQ1RR5S39rx2HOgb-kNFgc5foaH',
    'Al Hashr': 'https://drive.google.com/uc?id=1ccST56VInCqBgLYyQ-r0gvCxhfe4wp-T',
    'Al Mumtahanah': 'https://drive.google.com/uc?id=1F9POg6NGGMV5nzl0C-tNfWx_hF_hSIUz',
    'As Saf': 'https://drive.google.com/uc?id=1A6jODDDrmXVB0eUq0faOObiIEi_GolwD',
    'Al Jumuah': 'https://drive.google.com/uc?id=1c2jBXexKcOA2b-XP5s61nuh6XXgeQDQO',
    'Al Munafiqun': 'https://drive.google.com/uc?id=1mzVajLLgpKZmjL9TDedGuQ5QUXE6h5xI',
    'Al Taghabun': 'https://drive.google.com/uc?id=1-pcu4HayQ6TzRDb1uCo4rx8ZXfCA3YKn',
    'At Talaq': 'https://drive.google.com/uc?id=1j7ut0bHnfNdBeV_AdsZ7AQMSFltdCAna',
    'At Tahrim': 'https://drive.google.com/uc?id=1GJnikbf93MtI-dWHzFjQbJ-DFQ2_eGEU',
    'Al Mulk': 'https://drive.google.com/uc?id=1EayIP8jajIAGJTMil9P2AYfj1xSZn2V4',
    'Al Qalam': 'https://drive.google.com/uc?id=1y8WXChbTbso5i1UXXDg3fOpb63pbEkjq',
    'Al Haqqah': 'https://drive.google.com/uc?id=1i82HuZyf8GHeMnJepj4rVEZ5ISURBMH8',
    'Al Maarij': 'https://drive.google.com/uc?id=15txpbCyEl8jFSuR0o3Ewdryzy07yDKF6',
    'Nuh': 'https://drive.google.com/uc?id=15RMVD4UCZWJrbL5kWW4lGMdITWT83cwd',
    'Al Jinn': 'https://drive.google.com/uc?id=1YyKOc2PZf2LuFXdtOeZo8m9uLyvKnU30',
    'Al Muzammil': 'https://drive.google.com/uc?id=151eC8aHo4kBOwwhRG-35m9C-DdGAoq7i',
    'Al Mudaththir': 'https://drive.google.com/uc?id=1Xd4w9u82is349dslNJ1cuozW7_IzsA3Y',
    'Al Qiyamah': 'https://drive.google.com/uc?id=1boZB-9-uRKbfJMHY0Ek-D2h1wFYab6Rd',
    'Al Insan': 'https://drive.google.com/uc?id=1oIevKKxldtsH28jd-XhIdkWiikZN7bGL',
    'Al Mursalat': 'https://drive.google.com/uc?id=1I5qXA1fWLCmDGla_4Tj5DYlz7y-BkTCW',
    'An Naba': 'https://drive.google.com/uc?id=1kyd9_goGsfOEdoOkl7vWP0FYOCnWOUmy',
    'An Naziat': 'https://drive.google.com/uc?id=1fOVbAL_RWqMImKDGEuYf2EUGu-cv5vqw',
    'Abasa': 'https://drive.google.com/uc?id=1ACKw2MGshsCZz3TbTl3JhdGFFZ5p0eWF',
    'At Takwir': 'https://drive.google.com/uc?id=1lKVDFY3wSTBVIGZgQkX-V4c9IFSTr56X',
    'Al Infitar': 'https://drive.google.com/uc?id=1Zwaq4dxo3LNSB1HtaS5QxSvbrZ66nhqx',
    'Al Mutaffifin': 'https://drive.google.com/uc?id=1DDHxk_Fc4ZCvk7_DnICUvdJ221hHPsBw',
    'Al Inshiqaq': 'https://drive.google.com/uc?id=1Gzu6MxnRBwO_JNADYko9-Zj0mbQ-G2bJ',
    'Al Buruj': 'https://drive.google.com/uc?id=1MgtSAheB9GHVw3jynDWQ8DdM8VnfAXqa',
    'At Tariq': 'https://drive.google.com/uc?id=14IMfo6z796YWYTfTtbrpi77tA0HeisPZ',
    'Al Ala': 'https://drive.google.com/uc?id=1RDI-4VLVaWh5RBk0PrY76_FzlXCWiWCg',
    'Al Ghashiyah': 'https://drive.google.com/uc?id=1maCcoNOGgO_fYe6GnOwmyWZ8T_Uhw7zU',
    'Al Fajr': 'https://drive.google.com/uc?id=18oYlwOD6aPBqrIfl-QluTVypOrvX86rJ',
    'Al Balad': 'https://drive.google.com/uc?id=15Y1LzDbYKezmIVYYW8zequYeg_0OmjB3',
    'Ash Shams': 'https://drive.google.com/uc?id=1vqT5v752SfL6WBHJmeC61AUFFakLHOE7',
    'Al Layl': 'https://drive.google.com/uc?id=1k6Lr7SF9DC8ctKqZK7d4wrv3uHJpct2l',
    'Adh Dhuha': 'https://drive.google.com/uc?id=1wwFA1L0FW8TqnWtGudNlQXG8RcPc4h9D',
    'Al Inshirah': 'https://drive.google.com/uc?id=1RVIILiNanev0RJ-yK3-m8vNibzry3N-7',
    'At Tin': 'https://drive.google.com/uc?id=1LYGpQlLDkVKzh83fgk7UTHxKilaqENuX',
    'Al Alaq': 'https://drive.google.com/uc?id=1lX9FUEaKUd9jSxtva00PzUls8o1vd0G5',
    'Al Qadr': 'https://drive.google.com/uc?id=1pc9vYrhQ88mNupuQSTcjdEvLjEKrUzh0',
    'Al Bayinah': 'https://drive.google.com/uc?id=1Wv1zvrzjImxDiK6RD_3ong9ECXzccL2z',
    'Al Zalzalah': 'https://drive.google.com/uc?id=1Dwps0qw3GoHcELiD4YojWM_ouCGvvPS1',
    'Al Adiyah': 'https://drive.google.com/uc?id=1-Sa55UUd2nQuuqNbWk8SSEvkGuVgXWrd',
    'Al Qariah': 'https://drive.google.com/uc?id=1NCQXlbpYtTd4ZfroVCORMuS7thS3wfw6',
    'At Takathur': 'https://drive.google.com/uc?id=1zNdTJG7ZGzGDh1sd2FFSo7rEFO6oxtfy',
    'Al Asr': 'https://drive.google.com/uc?id=1q0juMThcweatV3Uk8L-tZbdosnqardl1',
    'Al Humazah': 'https://drive.google.com/uc?id=15aK2dLnOBqbTgXt4UqcqUElL_9h-tQ-6',
    'Al Fil': 'https://drive.google.com/uc?id=12dUHHXYSHXXrmmMar8lpy9wekIkU5Vsp',
    'Quraish': 'https://drive.google.com/uc?id=1-upE7AKJuZcYrkREkvE4Y3hh3B1NOY--',
    'Al Maun': 'https://drive.google.com/uc?id=1iyGAAtC1fY7c3gGNmugBRoWcABUYUwYh',
    'Al Kauthar': 'https://drive.google.com/uc?id=14KbyI4ye0Zlp8swlMFcpEX974puMDi5s',
    'Al Kafirun': 'https://drive.google.com/uc?id=1m06S_v_wSaskl9PPyERPrZIwpoMHDhl4',
    'An Nasr': 'https://drive.google.com/uc?id=1OnX_u9r7kIOwc_iF-Twk3xQwERRYftY2',
    'Al Masad': 'https://drive.google.com/uc?id=1fnkSXWU2rmTkfRatZC7cMbN67YMrlbTB',
    'Al Ikhlas': 'https://drive.google.com/uc?id=1-Z4924HMi5kE0pAIAMBZAPeM-Ie-bd59',
    'Al Falaq': 'https://drive.google.com/uc?id=1x3f_0PcOHbGUGtG1CMEsxz9HJb5F6cYs',
    'An Naas': 'https://drive.google.com/uc?id=1hyGmDUvwHzjDetUQ8HZywImPxPASyDG2'
}

num_verses_in_surah = {
    1: 7,   2: 286, 3: 200, 4: 176, 5: 120, 6: 165, 7: 206, 8: 75,  9: 129, 10: 109,
    11: 123, 12: 111, 13: 43,  14: 52,  15: 99,  16: 128, 17: 111, 18: 110, 19: 98,  20: 135,
    21: 112, 22: 78,  23: 118, 24: 64,  25: 77,  26: 227, 27: 93,  28: 88,  29: 69,  30: 60,
    31: 34,  32: 30,  33: 73,  34: 54,  35: 45,  36: 83,  37: 182, 38: 88,  39: 75,  40: 85,
    41: 54,  42: 53,  43: 89,  44: 59,  45: 37,  46: 35,  47: 38,  48: 29,  49: 18,  50: 45,
    51: 60,  52: 49,  53: 62,  54: 55,  55: 78,  56: 96,  57: 29,  58: 22,  59: 24,  60: 13,
    61: 14,  62: 11,  63: 11,  64: 18,  65: 12,  66: 12,  67: 30,  68: 52,  69: 52,  70: 44,
    71: 28,  72: 28,  73: 20,  74: 56,  75: 40,  76: 31,  77: 50,  78: 40,  79: 46,  80: 42,
    81: 29,  82: 19,  83: 36,  84: 25,  85: 22,  86: 17,  87: 19,  88: 26,  89: 30,  90: 20,
    91: 15,  92: 21,  93: 11,  94: 8,   95: 8,   96: 19,  97: 5,   98: 8,   99: 8,   100: 11,
    101: 11, 102: 8,  103: 3,   104: 9,  105: 5,   106: 4,   107: 7,   108: 3,   109: 6,   110: 3,
    111: 5,  112: 4,  113: 5,   114: 6
}


books = {
    'sahih-bukhari':7533,
    'sahih-muslim':7561,
    'al-tirmidhi':3956,
    'abu-dawood':5274,
    'ibn-e-majah':4341,
    'sunan-nasai':5761,
}

names = {
    'Ar Rahmaan':'The Most Merciful',
    'Ar Raheem':'The Especially Merciful',
    'Al Malik':'The Eternal Lord',
    'Al Quddus':'The Most Sacred',
    'As Salam':'The Giver of Peace',
    "Al Mu'min":'The Infuser of Faith',
    'Al Muhaymin':'The Protector',
    'Al Aziz':'The Mighty One',
    'Al Jabbar':'The Omnipotent One',
    'Al Mutakabbir':'The Dominant One',
    'Al Khaliq':'The Creator',
    'Al Baari':'The Maker',
    'Al Musawwir':'The Flawless Shaper',
    'Al Ghaffar':'The Great Forgiver',
    'Al Qahhar':'The All-Prevailing One',
    'Al Wahhab':'The Supreme Bestower',
    'Ar Razzaq':'The Total Provider',
    'Al Fattah':'The Supreme Solver',
    'Al Alim':'The All Knowing One',
    'Al Qabid':'The Restricting One',
    'Al Basit':'The Extendernt',
    'Al Khafid':'The Reducer',
    'Ar Rafi':'The Elevating One',
    "Al Mu'izz":'The Honourer',
    'Al Muzil':'The Abaser',
    'As Sami':'The All-Hearer',
    'Al Baseer':'The All-Seeing',
    'Al Hakam':'The Impartial Judge',
    'Al Adl':'The Just',
    'Al Lateef':'The Subtle One',
    'Al Khabir':'The All-Aware One',
    'Al Haleem':'The Forbearing',
    'Al Azeem':'The Magnificent',
    'Al Ghafoor':'The All-Forgiving',
    'Ash Shakur':'The Acknowledging One',
    'Al Aliyy':'The Sublime One',
    'Al Kabeer':'The Great One',
    'Al Hafiz':'The Guarding One',
    'Al Muqeet':'The Sustaining One',
    'Al Haseeb':'The Reckoning One',
    'Al Jaleel':'The Majestic One',
    'Al Karim':'The Bountiful One',
    'Ar Raqib':'The Watchful One',
    'Al Mujeeb':'The Responding One',
    "Al Wasi'":'The All-Pervading One',
    'Al Hakeem':'The Wise One',
    'Al Wadud':'The Loving One',
    'Al Majeed':'The Glorious One',
    "Al Ba'ith":'The Infuser of New Life',
    'Ash Shaheed':'The All Observing Witness',
    'Al Haqq':'The Embodiment of Truth',
    'Al Wakeel':'The Universal Trustee',
    'Al Qawiyy':'The Strong One',
    'Al Matin':'The Firm One',
    'Al Waliyy':'The Protecting Associate',
    'Al Hameed':'The Sole-Laudable One',
    'Al Muhsi':'The All-Enumerating One',
    'Al Mubdi':'The Originator',
    "Al Mu'id":'The Restorer',
    'Al Muhyi':'The Maintainer of Life',
    'Al Mumeet':'The Inflictor of Death',
    'Al Hayy':'The Eternally Living One',
    'Al Qayyum':'The Self-Subsisting One',
    'Al Waajid':'The Pointing One',
    'Al Maajid':'The All-Noble One',
    'Al Wahid':'The Only One',
    'Al Ahad':'The One',
    'As Samad':'The Eternal',
    'Al Qaadir':'The Omnipotent',
    'Al Muqtadir':'The Dominant',
    'Al Muqaddim':'The Expediter',
    "Al Mu'akhir":'The Postponer',
    'Al Awwal':'The First',
    'Al Akhir':'The Last',
    'Az Zaahir':'The Perceptible',
    'Al Baatin':'The Imperceptible',
    'Al Wali':'The Governor',
    "Al Muta'ali":'The Most Exalted',
    'Al Barr':'The Fountain-Head of Truth',
    'At Tawwab':'The Forgiver',
    'Al Muntaqim':'The Retaliator',
    'Al Afuw':'The Pardoner',
    "Ar Ra'uf":'The Benign',
    'Al Malikul-Mulk':'The Eternal Possessor of Sovereignty',
    'Zul-Jalaali-wal-Ikram':'The Possessor of Majesty and Honor',
    'Al Muqsit':'The Just',
    "Al Jaami'":'The Gatherer',
    'Al Ghaniyy':'The Self-Sufficient',
    'Al Mughni':'The Enricher',
    "Al Maani'":'The Preventer',
    'Ad Daarr':'The Distressor',
    "An Naafi'":'The Benefitor',
    'An Noor':'The Light',
    'Al Haadi':'The Guide',
    "Al Badi'":'The Unique',
    'Al Baaqi':'The Everlasting',
    'Al Waarith':'The Heir',
    'Ar Rasheed':'The Guide to Path of Rectitude',
    'As Sabur':'The Patient'
}

# Ignore
"""
num_hadith_in_chapters = {
    'sahih-bukhari': {
        'Revelation':[1, 7],
        'Belief':[8, 58],
        'Knowledge':[59, 134],
        "Ablutions (Wudu')":[135, 247],
        'Bathing (Ghusl)':[248, 293],
        'Menstrual Periods':[294, 333],
        'Rubbing hands and feet with dust (Tayammum)':[334, 348],
        'Prayers (Salat)':[349, 520],
        'Times of the Prayers':[521, 602],
        'Call to Prayers (Adhaan)':[603, 734],
        'Call to Prayers (Adhaan)(Sufa Tu Salat)':[735, 875],
        'Friday Prayer':[876, 941],
        'Fear Prayer':[942, 947],
        'The Two Festivals (Eids)':[948, 989],
        'Witr Prayer':[990, 1040],
        'Invoking Allah for Rain (Istisqaa)':[1041, 1039],
        'Eclipses':[1040, 1065],
        "Prostration During Recital of Qur'an":[1067, 1079],
        'Shortening the Prayers (At-Taqseer)':[1080, 1119],
        'Prayer at Night (Tahajjud)':[1120, 1187],
        'Virtues of Prayer at Masjid Makkah and Madinah':[1188, 1197],
        'Actions while Praying':[1198, 1223],
        'Forgetfulness in Prayer':[1224, 1236],
        "Funerals (Al-Janaa'iz)":[1237, 1394],
        'Obligatory Charity Tax (Zakat)':[1395, 1512],
        'Hajj (Pilgrimage)':[1513, 1771],
        '`Umrah (Minor pilgrimage)':[1773, 1805],
        'Pilgrims Prevented from Completing the Pilgrimage':[1806, 1820],
        'Penalty of Hunting while on Pilgrimage':[1821, 1866],
        'Virtues of Madinah':[1867, 1890],
        'Fasting':[1891, 2007]
    },
    'sahih-muslim': {},
    'al-tirmidhi': {},
    'abu-dawood': {},
    'ibn-e-majah': {},
    'sunan-nasai': {},
}
"""